### ISSUE TITLE
代码跑不起来，报错如下

### ISSUE THREAD

**Issue by weileiChina** [wuwhs/minxiuWeather#1]
thirdScriptError 
 sdk uncaught third Error 
 key值不能为空 
 Error: key值不能为空
    at new b (http://127.0.0.1:44000/appservice/lib/qqmap-wx-jssdk.min.js:93:13)
    at http://127.0.0.1:44000/appservice/api/index.js:11:15
    at require (http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718745)
    at http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718354
    at http://127.0.0.1:44000/appservice/app.js:7:11
    at require (http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718745)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:44000/appservice/appservice?t=1545187471671:1176:23)

**Comment by wuwhs** [comment]
> thirdScriptError
> sdk uncaught third Error
> key值不能为空
> Error: key值不能为空
> at new b (http://127.0.0.1:44000/appservice/lib/qqmap-wx-jssdk.min.js:93:13)
> at http://127.0.0.1:44000/appservice/api/index.js:11:15
> at require (http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718745)
> at http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718354
> at http://127.0.0.1:44000/appservice/app.js:7:11
> at require (http://127.0.0.1:44000/appservice/__dev__/WAService.js:1:718745)
> at :1:1
> at HTMLScriptElement.scriptLoaded (http://127.0.0.1:44000/appservice/appservice?t=1545187471671:1176:23)

你需要申请个人腾讯位置服务的密钥（key），更多请查看[相关问题反馈](https://github.com/wuwhs/minxiuWeather#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88)

**Comment by weileiChina** [comment]
好的，可以了。谢谢

**Comment by Meteorsss** [comment]
> 好的，可以了。谢谢

老哥问一下，你自己申请的和风天气api可以用么？为啥我的在这个小程序里用不了，其他地方可以
