### ISSUE TITLE
缺少databaseGuide

### ISSUE THREAD

**Issue by quewen08** [wuwhs/minxiuWeather#2]
错误如下  ./pages/databaseGuide/databaseGuide.wxml not found

**Comment by wuwhs** [comment]
> 错误如下 ./pages/databaseGuide/databaseGuide.wxml not found

你好，你再确认下，当前项目没有 databaseGuide 页哦

**Comment by trover-gaoyou** [comment]
> > 错误如下 ./pages/databaseGuide/databaseGuide.wxml not found
> 
> 你好，你再确认下，当前项目没有 databaseGuide 页哦

project.config.json的配置项里面有的啊  在第31行的配置项里

**Comment by wuwhs** [comment]
> > 错误如下 ./pages/databaseGuide/databaseGuide.wxml not found
> 
> 你好，你再确认下，当前项目没有 databaseGuide 页哦

抱歉，忘了说明以下了，这个是我的云开发模式的默认生产的配置，你可以删掉改成
```js
"miniprogram": {
	"current": -1,
	"list": []
}
```

**Comment by Meteorsss** [comment]
> 错误如下 ./pages/databaseGuide/databaseGuide.wxml not found

老哥问一下，你自己申请的和风天气api可以用么？为啥我的在这个小程序里用不了，其他地方可以
