### ISSUE TITLE
cond图片颜色问题

### ISSUE THREAD

**Issue by hjaiim** [wuwhs/minxiuWeather#3]
cond图片,我是在和风天气打包下载的,然后图片都是蓝色,看你的图片资源都是白色的.请问您是怎么弄的,或者可以发给我一份吗,蓝色的太难看了

**Comment by wuwhs** [comment]
> cond图片,我是在和风天气打包下载的,然后图片都是蓝色,看你的图片资源都是白色的.请问您是怎么弄的,或者可以发给我一份吗,蓝色的太难看了

我是用PS处理的，图层 > 图层样式 > 颜色叠加

**Comment by hjaiim** [comment]
> > cond图片,我是在和风天气打包下载的,然后图片都是蓝色,看你的图片资源都是白色的.请问您是怎么弄的,或者可以发给我一份吗,蓝色的太难看了
> 
> 我是用PS处理的，图层 > 图层样式 > 颜色叠加

好的,十分感谢.

**Comment by Meteorsss** [comment]
> cond图片,我是在和风天气打包下载的,然后图片都是蓝色,看你的图片资源都是白色的.请问您是怎么弄的,或者可以发给我一份吗,蓝色的太难看了
老哥问一下，你自己申请的和风天气api可以用么？为啥我的在这个小程序里用不了，其他地方可以
